### ISSUE TITLE
skip forward/backward

### ISSUE THREAD

**Issue by jamen** [audiojs/audio-play#11]
Would skipping forward/backward on the buffer fit inside the use of this module?  For example `player.forward(duration?)`/`.backward(duration?)`  Also taking into account when buffer is playing/paused. 

If this is possible, it would be even cooler to potentially adapt the interface to streams.  So for example it lazy loads over the network (buffers data as it plays), and if you skip forward it can compensate with loading that data, and with skipping backwards it could just refer back to what the stream has received.

**Comment by dfcreative** [comment]
@jamen alternatively we can do 'currentTime' writable, that is done so in web-audio-api

**Comment by jamen** [comment]
@dfcreative that works even better.  :+1:
