### ISSUE TITLE
Please package pre-compiled version

### ISSUE THREAD

**Issue by peterbe** [audiojs/audio-play#16]
I use `create-react-app` and one of my dependencies is `audio-play`. Sadly I can't build my `create-react-app` due to this error:
```
▶ yarn build
yarn run v1.6.0
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/audio-play/browser.js:16
```

As per [their instructions](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) to resolve this it says

> "Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled."

So can we please have a pre-compiled version within the package?

**Comment by latel** [comment]
same problems here, it's hard to play babel 7

**Comment by derhuerst** [comment]
Do you know *why* it doesn't minify/compile?

**Comment by dy** [comment]
@latel  @peterbe try 2.2.1 - that has ES5 code. Tested that with uglifyjs - works fine.
If that does not help, the problem is not in this package.

**Comment by peterbe** [comment]
It works! I'm using `audio-loader` and `audio-play` and now I can run `yarn run build` in my create-react-app project. Thanks!
